# surrealdb
[[language]]
name = "surql"
scope = "source.surql"
file-types = ["surql"]
comment-token = "--"
indent = { tab-width = 4, unit = "    " }
roots = []
injection-regex = "surql"

# elixir
[language-server.elixir-ls]
config = { elixirLS.dialyzerEnabled = true }

# rust
[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
rulers = [100]

# python
[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[language-server.ruff]
command = "ruff-lsp"
config = { settings = { args = ["--extend-select", "I,RUF"] } }

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
auto-format = false
formatter = {command = "ruff", args = ["format", "-"]}

# trying to get pyright to work
# scope = "source.python"
# injection-regex = "python"
# file-types = ["py","pyi","py3","pyw","ptl",".pythonstartup",".pythonrc","SConstruct"]
# shebangs = ["python"]
# roots = ["setup.py", "setup.cfg", "pyproject.toml"]
# comment-token = "#"
# indent = { tab-width = 4, unit = "    " }

# prettier
[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
