[mgr]
prepend_keymap = [
  { on = "E", run = "shell ~/bin/yhx-switch-hx" },
  { on = "L", run = "shell ~/bin/yhx-switch-lazygit" },
  { on = "n", run = "leave", desc = "left"  },
  { on = "e", run = "arrow 1", desc = "down"  },
  { on = "i", run = "arrow -1", desc = "up"    },
  { on = "o", run = "enter", desc = "right" },
]
