###############################################################################
# Rust
###############################################################################
[language-server.rust-analyzer]
command = "rustup"
args = ["run", "nightly", "rust-analyzer"]

[language-server.rust-analyzer.config]
# config = { completion = { autoimport = { enable = false }, postfix = { enable = false }, limit = 200 } }
# procMacro = { enable = false }
diagnostics = { disabled = ["unlinked-file"] }
check.command = "clippy"
cargo.features = "all"

[[language]]
name = "rust"

###############################################################################
# Python
###############################################################################
[[language]]
name = "python"
language-servers = ["ruff", "pyright"]

[language-server.ty.config]
diagnosticMode = "workspace"
